language: node_js
sudo: false
cache:
  directories:
    - "node_modules"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
node_js:
  - 10
  - 8.10.0
script:
  - npm test
jobs:
  include:
    - stage: release
      if: branch = master
      node_js: 10
      script:
        - npm run release
notifications:
  email:
    on_success: never
    on_failure: always
