language: node_js
sudo: false
cache:
  directories:
    - "node_modules"
node_js:
  - "8.10.0"
  - "10"
script:
  - npm test
  - npm run release
notifications:
  email:
    on_success: never
    on_failure: always
