name: Continuous Delivery

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  ci-cd:
    name: Continuous Delivery
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message , 'skip ci')"
    env:
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.4
      - name: Cache Node Modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
      - name: Deploy
        if: github.ref == 'refs/heads/master'
        run: npm run release
